package com.wbg.treasure.entity;

public class GetContent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column get_content.UUID
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column get_content.page_uuid
     *
     * @mbg.generated
     */
    private String pageUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column get_content.get_time
     *
     * @mbg.generated
     */
    private String getTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column get_content.get_statis
     *
     * @mbg.generated
     */
    private String getStatis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column get_content.key_connent
     *
     * @mbg.generated
     */
    private String keyConnent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column get_content.is_award
     *
     * @mbg.generated
     */
    private String isAward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column get_content.number_of_periods
     *
     * @mbg.generated
     */
    private String numberOfPeriods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column get_content.page_address
     *
     * @mbg.generated
     */
    private String pageAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column get_content.charset_code
     *
     * @mbg.generated
     */
    private String charsetCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column get_content.page_connent
     *
     * @mbg.generated
     */
    private String pageConnent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column get_content.UUID
     *
     * @return the value of get_content.UUID
     *
     * @mbg.generated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column get_content.UUID
     *
     * @param uuid the value for get_content.UUID
     *
     * @mbg.generated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column get_content.page_uuid
     *
     * @return the value of get_content.page_uuid
     *
     * @mbg.generated
     */
    public String getPageUuid() {
        return pageUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column get_content.page_uuid
     *
     * @param pageUuid the value for get_content.page_uuid
     *
     * @mbg.generated
     */
    public void setPageUuid(String pageUuid) {
        this.pageUuid = pageUuid == null ? null : pageUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column get_content.get_time
     *
     * @return the value of get_content.get_time
     *
     * @mbg.generated
     */
    public String getGetTime() {
        return getTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column get_content.get_time
     *
     * @param getTime the value for get_content.get_time
     *
     * @mbg.generated
     */
    public void setGetTime(String getTime) {
        this.getTime = getTime == null ? null : getTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column get_content.get_statis
     *
     * @return the value of get_content.get_statis
     *
     * @mbg.generated
     */
    public String getGetStatis() {
        return getStatis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column get_content.get_statis
     *
     * @param getStatis the value for get_content.get_statis
     *
     * @mbg.generated
     */
    public void setGetStatis(String getStatis) {
        this.getStatis = getStatis == null ? null : getStatis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column get_content.key_connent
     *
     * @return the value of get_content.key_connent
     *
     * @mbg.generated
     */
    public String getKeyConnent() {
        return keyConnent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column get_content.key_connent
     *
     * @param keyConnent the value for get_content.key_connent
     *
     * @mbg.generated
     */
    public void setKeyConnent(String keyConnent) {
        this.keyConnent = keyConnent == null ? null : keyConnent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column get_content.is_award
     *
     * @return the value of get_content.is_award
     *
     * @mbg.generated
     */
    public String getIsAward() {
        return isAward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column get_content.is_award
     *
     * @param isAward the value for get_content.is_award
     *
     * @mbg.generated
     */
    public void setIsAward(String isAward) {
        this.isAward = isAward == null ? null : isAward.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column get_content.number_of_periods
     *
     * @return the value of get_content.number_of_periods
     *
     * @mbg.generated
     */
    public String getNumberOfPeriods() {
        return numberOfPeriods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column get_content.number_of_periods
     *
     * @param numberOfPeriods the value for get_content.number_of_periods
     *
     * @mbg.generated
     */
    public void setNumberOfPeriods(String numberOfPeriods) {
        this.numberOfPeriods = numberOfPeriods == null ? null : numberOfPeriods.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column get_content.page_address
     *
     * @return the value of get_content.page_address
     *
     * @mbg.generated
     */
    public String getPageAddress() {
        return pageAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column get_content.page_address
     *
     * @param pageAddress the value for get_content.page_address
     *
     * @mbg.generated
     */
    public void setPageAddress(String pageAddress) {
        this.pageAddress = pageAddress == null ? null : pageAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column get_content.charset_code
     *
     * @return the value of get_content.charset_code
     *
     * @mbg.generated
     */
    public String getCharsetCode() {
        return charsetCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column get_content.charset_code
     *
     * @param charsetCode the value for get_content.charset_code
     *
     * @mbg.generated
     */
    public void setCharsetCode(String charsetCode) {
        this.charsetCode = charsetCode == null ? null : charsetCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column get_content.page_connent
     *
     * @return the value of get_content.page_connent
     *
     * @mbg.generated
     */
    public String getPageConnent() {
        return pageConnent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column get_content.page_connent
     *
     * @param pageConnent the value for get_content.page_connent
     *
     * @mbg.generated
     */
    public void setPageConnent(String pageConnent) {
        this.pageConnent = pageConnent == null ? null : pageConnent.trim();
    }
}