package com.wbg.treasure.entity;

public class ScheduleLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_log.UUID
     *
     * @mbg.generated
     */
    private Integer uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_log.class_name
     *
     * @mbg.generated
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_log.start_time
     *
     * @mbg.generated
     */
    private String startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_log.end_time
     *
     * @mbg.generated
     */
    private String endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_log.datasource
     *
     * @mbg.generated
     */
    private String datasource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_log.status_log
     *
     * @mbg.generated
     */
    private String statusLog;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_log.UUID
     *
     * @return the value of schedule_log.UUID
     *
     * @mbg.generated
     */
    public Integer getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_log.UUID
     *
     * @param uuid the value for schedule_log.UUID
     *
     * @mbg.generated
     */
    public void setUuid(Integer uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_log.class_name
     *
     * @return the value of schedule_log.class_name
     *
     * @mbg.generated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_log.class_name
     *
     * @param className the value for schedule_log.class_name
     *
     * @mbg.generated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_log.start_time
     *
     * @return the value of schedule_log.start_time
     *
     * @mbg.generated
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_log.start_time
     *
     * @param startTime the value for schedule_log.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_log.end_time
     *
     * @return the value of schedule_log.end_time
     *
     * @mbg.generated
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_log.end_time
     *
     * @param endTime the value for schedule_log.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_log.datasource
     *
     * @return the value of schedule_log.datasource
     *
     * @mbg.generated
     */
    public String getDatasource() {
        return datasource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_log.datasource
     *
     * @param datasource the value for schedule_log.datasource
     *
     * @mbg.generated
     */
    public void setDatasource(String datasource) {
        this.datasource = datasource == null ? null : datasource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_log.status_log
     *
     * @return the value of schedule_log.status_log
     *
     * @mbg.generated
     */
    public String getStatusLog() {
        return statusLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_log.status_log
     *
     * @param statusLog the value for schedule_log.status_log
     *
     * @mbg.generated
     */
    public void setStatusLog(String statusLog) {
        this.statusLog = statusLog == null ? null : statusLog.trim();
    }
}