package com.wbg.treasure.entity;

public class Schedule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.UUID
     *
     * @mbg.generated
     */
    private Integer uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.task_name
     *
     * @mbg.generated
     */
    private String taskName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.task_description
     *
     * @mbg.generated
     */
    private String taskDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.class_name
     *
     * @mbg.generated
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.param
     *
     * @mbg.generated
     */
    private String param;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.task_status
     *
     * @mbg.generated
     */
    private String taskStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.second
     *
     * @mbg.generated
     */
    private String second;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.minute
     *
     * @mbg.generated
     */
    private String minute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.hour
     *
     * @mbg.generated
     */
    private String hour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.day
     *
     * @mbg.generated
     */
    private String day;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.month
     *
     * @mbg.generated
     */
    private String month;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.weekday
     *
     * @mbg.generated
     */
    private String weekday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.year
     *
     * @mbg.generated
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.cron_expression
     *
     * @mbg.generated
     */
    private String cronExpression;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.UUID
     *
     * @return the value of schedule.UUID
     *
     * @mbg.generated
     */
    public Integer getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.UUID
     *
     * @param uuid the value for schedule.UUID
     *
     * @mbg.generated
     */
    public void setUuid(Integer uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.task_name
     *
     * @return the value of schedule.task_name
     *
     * @mbg.generated
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.task_name
     *
     * @param taskName the value for schedule.task_name
     *
     * @mbg.generated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.task_description
     *
     * @return the value of schedule.task_description
     *
     * @mbg.generated
     */
    public String getTaskDescription() {
        return taskDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.task_description
     *
     * @param taskDescription the value for schedule.task_description
     *
     * @mbg.generated
     */
    public void setTaskDescription(String taskDescription) {
        this.taskDescription = taskDescription == null ? null : taskDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.class_name
     *
     * @return the value of schedule.class_name
     *
     * @mbg.generated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.class_name
     *
     * @param className the value for schedule.class_name
     *
     * @mbg.generated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.param
     *
     * @return the value of schedule.param
     *
     * @mbg.generated
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.param
     *
     * @param param the value for schedule.param
     *
     * @mbg.generated
     */
    public void setParam(String param) {
        this.param = param == null ? null : param.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.task_status
     *
     * @return the value of schedule.task_status
     *
     * @mbg.generated
     */
    public String getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.task_status
     *
     * @param taskStatus the value for schedule.task_status
     *
     * @mbg.generated
     */
    public void setTaskStatus(String taskStatus) {
        this.taskStatus = taskStatus == null ? null : taskStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.second
     *
     * @return the value of schedule.second
     *
     * @mbg.generated
     */
    public String getSecond() {
        return second;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.second
     *
     * @param second the value for schedule.second
     *
     * @mbg.generated
     */
    public void setSecond(String second) {
        this.second = second == null ? null : second.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.minute
     *
     * @return the value of schedule.minute
     *
     * @mbg.generated
     */
    public String getMinute() {
        return minute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.minute
     *
     * @param minute the value for schedule.minute
     *
     * @mbg.generated
     */
    public void setMinute(String minute) {
        this.minute = minute == null ? null : minute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.hour
     *
     * @return the value of schedule.hour
     *
     * @mbg.generated
     */
    public String getHour() {
        return hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.hour
     *
     * @param hour the value for schedule.hour
     *
     * @mbg.generated
     */
    public void setHour(String hour) {
        this.hour = hour == null ? null : hour.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.day
     *
     * @return the value of schedule.day
     *
     * @mbg.generated
     */
    public String getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.day
     *
     * @param day the value for schedule.day
     *
     * @mbg.generated
     */
    public void setDay(String day) {
        this.day = day == null ? null : day.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.month
     *
     * @return the value of schedule.month
     *
     * @mbg.generated
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.month
     *
     * @param month the value for schedule.month
     *
     * @mbg.generated
     */
    public void setMonth(String month) {
        this.month = month == null ? null : month.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.weekday
     *
     * @return the value of schedule.weekday
     *
     * @mbg.generated
     */
    public String getWeekday() {
        return weekday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.weekday
     *
     * @param weekday the value for schedule.weekday
     *
     * @mbg.generated
     */
    public void setWeekday(String weekday) {
        this.weekday = weekday == null ? null : weekday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.year
     *
     * @return the value of schedule.year
     *
     * @mbg.generated
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.year
     *
     * @param year the value for schedule.year
     *
     * @mbg.generated
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.cron_expression
     *
     * @return the value of schedule.cron_expression
     *
     * @mbg.generated
     */
    public String getCronExpression() {
        return cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.cron_expression
     *
     * @param cronExpression the value for schedule.cron_expression
     *
     * @mbg.generated
     */
    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression == null ? null : cronExpression.trim();
    }
}