package com.wbg.treasure.entity;

public class WebsiteInformation {
    @Override
    public String toString() {
        return "WebsiteInformation{" +
                "uuid=" + uuid +
                ", pageAddress='" + pageAddress + '\'' +
                ", pageName='" + pageName + '\'' +
                ", pageStatus='" + pageStatus + '\'' +
                ", pageTime='" + pageTime + '\'' +
                ", pageRemarks='" + pageRemarks + '\'' +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_information.uuid
     *
     * @mbg.generated
     */
    private Integer uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_information.page_address
     *
     * @mbg.generated
     */
    private String pageAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_information.page_name
     *
     * @mbg.generated
     */
    private String pageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_information.page_status
     *
     * @mbg.generated
     */
    private String pageStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_information.page_time
     *
     * @mbg.generated
     */
    private String pageTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_information.page_remarks
     *
     * @mbg.generated
     */
    private String pageRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_information.uuid
     *
     * @return the value of website_information.uuid
     *
     * @mbg.generated
     */
    public Integer getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_information.uuid
     *
     * @param uuid the value for website_information.uuid
     *
     * @mbg.generated
     */
    public void setUuid(Integer uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_information.page_address
     *
     * @return the value of website_information.page_address
     *
     * @mbg.generated
     */
    public String getPageAddress() {
        return pageAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_information.page_address
     *
     * @param pageAddress the value for website_information.page_address
     *
     * @mbg.generated
     */
    public void setPageAddress(String pageAddress) {
        this.pageAddress = pageAddress == null ? null : pageAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_information.page_name
     *
     * @return the value of website_information.page_name
     *
     * @mbg.generated
     */
    public String getPageName() {
        return pageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_information.page_name
     *
     * @param pageName the value for website_information.page_name
     *
     * @mbg.generated
     */
    public void setPageName(String pageName) {
        this.pageName = pageName == null ? null : pageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_information.page_status
     *
     * @return the value of website_information.page_status
     *
     * @mbg.generated
     */
    public String getPageStatus() {
        return pageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_information.page_status
     *
     * @param pageStatus the value for website_information.page_status
     *
     * @mbg.generated
     */
    public void setPageStatus(String pageStatus) {
        this.pageStatus = pageStatus == null ? null : pageStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_information.page_time
     *
     * @return the value of website_information.page_time
     *
     * @mbg.generated
     */
    public String getPageTime() {
        return pageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_information.page_time
     *
     * @param pageTime the value for website_information.page_time
     *
     * @mbg.generated
     */
    public void setPageTime(String pageTime) {
        this.pageTime = pageTime == null ? null : pageTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_information.page_remarks
     *
     * @return the value of website_information.page_remarks
     *
     * @mbg.generated
     */
    public String getPageRemarks() {
        return pageRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_information.page_remarks
     *
     * @param pageRemarks the value for website_information.page_remarks
     *
     * @mbg.generated
     */
    public void setPageRemarks(String pageRemarks) {
        this.pageRemarks = pageRemarks == null ? null : pageRemarks.trim();
    }
}